### ISSUE TITLE
Use MasterServers.AS ip to host game always pending in waitPayload

### ISSUE THREAD

**Issue by 2van** [SkeldJS/SkeldJS#1]

**Comment by 2van** [comment]
Use MasterServers.Asian' ip to host game always stuck at waitPayload, the first reliable packet is below 
{
  bound: 'client',
  op: 1,
  nonce: 1,
  payloads: [
    {
      tag: 1,
      bound: 'client',
      error: false,
      code: 8,
      clientid: 1701336152,
      hostid: 1835099936
    }
  ]
}

**Comment by edqx** [comment]
The packet is malformed because of a serialisation issue, the reason why it isn't working should be revealed in there.

**Comment by edqx** [comment]
After testing myself and fixing packet deserialisation for join packets, turns out the game options are invalid for Asia servers for some reason. https://au.weakeyes.dev/vS7e4zNfH3HCfjeBGkon
Adding `{ version: 2 }` to the game host options should fix it.
```js
const code = await client.host({
    version: 2,
    players: 10,
    map: skeldjs.MapID.TheSkeld,
    impostors: 2
});
```
