### ISSUE TITLE
Initialize player transform positions to the correct player spawn point

### ISSUE THREAD

**Issue by danbudworthmead** [SkeldJS/SkeldJS#26]
Currently, players transform position is only set when they first move. Impostor used to have the same issue and this was solved by setting the player's transform.position to the spawn point.

**Comment by edqx** [comment]
Fixed in 245a1b1c0d24d0932dc783f6107629a72e2c7c6c and 9bf67a8820d914f51eebaa2ff1ac464f938ed6b9
