### ISSUE TITLE
can't receive packet once game end

### ISSUE THREAD

**Issue by 2van** [SkeldJS/SkeldJS#3]
Join a game and do not spawn, will receive packet normally, but receive no more packet after "EndGame" event

**Comment by 2van** [comment]
above issue use @skeldjs/client v2.2.6 or v2.3.3

**Comment by 2van** [comment]
ok, i got it. i should join game again when gameEnd event emitted.

**Comment by edqx** [comment]
I apologise, I didn't see this issue, the client should disconnect when the game ends, requiring you to join back. Glad you sorted it.
