### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by justekoro** [SkeldJS/SkeldJS#31]
Hi,
When I try to run the following code, it just keeps on « connecting » indefinitely.
Any solutions?

```
const skeldjs = require('@skeldjs/client');
const util = require('@skeldjs/util');
(async()=>{
  
    const client = new skeldjs.SkeldjsClient('2022.3.29', {
        chatMode: skeldjs.QuickChatMode.QuickChat
    });
    console.log("client created")

    console.log("Connecting..");
    client.connect(skeldjs.OfficialServers.EU, "testhello").then(async connected => {
      console.log("Connected")
          console.log("Connected, finding games");

    const games = await client.findGames();
    console.log("Received games list");
const game = games[games.length-1];
console.log("Attempting to join game",game)
const formatted = util.Int2Code(game.code);
console.log("Formatted code:",formatted);
const code = await client.joinGame(formatted);

console.log("Joined game", game);

    await client.myPlayer.control.checkName("testhello");
    await client.myPlayer.control.checkColor(2);

    let players = Array.from(client.players.entries())
    //console.log(players)    
    console.log("Joined!");
  client.on("room.assignRoles", (evt) => {
    console.log("Roles assigned...",evt);
  })

  client.on("player.spawn", (evt) => {
    console.log("A player spawned",evt.player.username);
  })
    }).catch(err => {
      console.log("An error occured.",err);
    })

})()
```

(all the packages used are updated in the latest version, both 2.15.19)

**Comment by edqx** [comment]
Hi, you need to replace your game version with `2022.2.2.0`, which is the internal version used in networking.

They don't always change the networking version when a new game version is released, because it's helpful to keep backwards-compatibility for clients that aren't fully updated yet.

Hope this helped.

**Comment by justekoro** [comment]
thank you, it works now!
tho, I’m unable to join a game. last logged line is « formatted code: XXXXXX ».
any solutions?

**Comment by justekoro** [comment]
hi, bumping the issue

**Comment by edqx** [comment]
Sorry, I'm not sure what you mean that you're unable to join. You mean your bot - or you as a player?

Feel free to join the discord, I might be able to help you better. I can post the fix here.

**Comment by justekoro** [comment]
I mean my bot is unable to join nor create a game…

**Comment by justekoro** [comment]
I just joined the Discord. koro#3351
