### ISSUE TITLE
will this ever work again?

### ISSUE THREAD

**Issue by 0tv** [SkeldJS/SkeldJS#34]

**Comment by edqx** [comment]
I have some commits for updates just before the Fungle map, but it isn't likely that I will put in any time personally for the map update. If anyone has a PR at any point then I'll gladly review and accept it.

**Comment by Appu26J** [comment]
you should push those commits

**Comment by edqx** [comment]
You're right, I'll have a look later at getting them pushed. 🙂

**Comment by edqx** [comment]
Fixed in `2.16.0`: 782d32510cc4dff601f70ddf74736cce4a83cba5..4d41bd54ea1c633b3b2d76719cd8088627e52d4e!

**Comment by edqx** [comment]
Oops- accidentally removed a bunch of tooling dependencies... hope no one needed those.
