### ISSUE TITLE
how to connect client to private server

### ISSUE THREAD

**Issue by epicwappy20** [SkeldJS/SkeldJS#5]
how to connect client to private server

**Comment by edqx** [comment]
If you mean like an Impostor or NodePolus private server, you can just provide the IP for that in the `SkeldjsClient#connect()` method.
For example, if you want to connect to a private server hosted locally, you can use
```ts
const client = new SkeldjsClient;
client.connect("127.0.0.1", "weakeyes", 123);
```
Note that the `123` can be a random integer if the server that you're connecting to doesn't support authorization.
See https://skeldjs.github.io/SkeldJS/classes/client.skeldjsclient.html#connect for more information.
