### ISSUE TITLE
how do i start the client

### ISSUE THREAD

**Issue by epicwappy20** [SkeldJS/SkeldJS#6]
ive been trying for a while

**Comment by epicwappy20** [comment]
im not sure i installed it right

**Comment by edqx** [comment]
Hi, I'm not quite sure what you mean.
You can see installation instructions for skeldjs in the README if you're having issues installing it.
Also note that you might have been trying to install the region server which currently does not work, as I've mainly been focusing on the client.

If you want to start a programmable client, see the `packages/client/ts/example` directory for code examples.

**Comment by edqx** [comment]
Feel free to reopen if you can't get it working.
